### ISSUE TITLE
Fact Completion Data

### ISSUE THREAD

**Issue by xwhan** [rloganiv/kglm-model#44]
Hi, I am quite interested in the fact completion task in your paper. Can you provide the data that you used for this particular experiment? Thanks!

**Comment by rloganiv** [comment]
Certainly, the fact completion data is available here: [link](https://drive.google.com/file/d/1awiXa66AWyRmT5Ru_3eKH5Exp_Moy6_l/view?usp=sharing)

Sorry about the delay!
