### ISSUE TITLE
Usage of Perplexity Evaluation

### ISSUE THREAD

**Issue by YUE-FAN** [rloganiv/kglm-model#45]
Hi,

Thanks for the awesome work. I have a small question about evaluation:

In the following command, I only have model_archive_file after training, how can I get a sampler_archive_file?

`python -m kglm.run evaluate-perplexity \
    [model_archive_file] \
    [sampler_archive_file] \
    [input_file]`

**Comment by rloganiv** [comment]
Hi,

Thanks for the kind words! To obtain a sampler checkpoint you will need to train a  `kglm-disc` model.

**Comment by rloganiv** [comment]
Did this resolve your issue?

**Comment by YUE-FAN** [comment]
Yes, it works perfectly, thanks a lot. Sorry for getting back late
