### ISSUE TITLE
About the training

### ISSUE THREAD

**Issue by Lightyounger** [rloganiv/kglm-model#47]
Hello, I would like to ask where your [path to config], I use json file which under the folder of "kglm-model/kglm/tests/fixtures/training_config/ ", but it seem to go wrong with " RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'  ".

**Comment by rloganiv** [comment]
Hi @Lightyounger,

Can you provide the full stack trace as well as the config you are using?

**Comment by Lightyounger** [comment]
Hi,

    Thank you for your reply. This is my relevant config and  the error of code running .
    And I use 'train kglm-model/kglm/tests/fixtures/training_config/alias_copynet.json'  as  the 'train [path to config]' , I don't know if that's right.
   Thank you very much for your time! 



------------------ 原始邮件 ------------------
发件人: "Robert L. Logan IV"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 凌晨3:14
收件人: "rloganiv/kglm-model"<kglm-model@noreply.github.com>;
抄送: "许晓泓"<464629017@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [rloganiv/kglm-model] About the training (#47)




Hi @Lightyounger,
 
Can you provide the full stack trace as well as the config you are using?

**Comment by rloganiv** [comment]
Pasting your response email here in case anyone else has this issue:

>     Thank you for your reply. This is my relevant config and  the error of code running .
>     And I use 'train kglm-model/kglm/tests/fixtures/training_config/alias_copynet.json'  as  the 'train [path to config]' , I don't know if that's right.

The model used in that config is the `alias-copynet`. This was used for early experiments (not included in our paper), and does not appear to be working with our current codebase.

If you want to train the KGLM model (e.g. the one described in the paper) you should use this config as a template: https://github.com/rloganiv/kglm-model/blob/master/experiments/kglm.jsonnet

**Comment by pkang2017** [comment]
Dear rloganiv, thank you for your amazing work. I also encountered this problem during training even if I change the config as what you said? Any ideas would be appreciated.

Thank you!

**Comment by rloganiv** [comment]
Hi @pkang2017, happy to help! Just to confirm, you are also getting this error?
```
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'
```
If so, I noticed recently that this can occur when using earlier versions of PyTorch. Try upgrading to PyTorch==1.1.0 and let me know if the issue persists.

**Comment by Shengqiang-Zhang** [comment]
I encountered the same RuntimeError problem, and I use PyTorch == 1.2.0.
But I solved this problem by modifying the following codes of "kglm/models/kglm.py":
1. In line 980, modify `flattened_mask = mask.view(-1, 1).byte()` to `flattened_mask = mask.view(-1, 1).bool()`
2. In line 1044 & 1045, modify `mask.byte()` to `mask.bool()`

**Comment by rloganiv** [comment]
@Shengqiang-Zhang That makes sense, I checked the release log and apparently there are breaking changes in PyTorch==1.2.0 concerning the behavior of bytes vs. bools. See: https://github.com/pytorch/pytorch/releases.

In order to avoid issues with non-backwards compatability I would still recommend using PyTorch==1.1.0 over this fix. The version of AllenNLP used also is affected by this byte -> bool issue.

**Comment by rloganiv** [comment]
Closed since `requirements.txt` now explicitly requires PyTorch==1.1.0
