### ISSUE TITLE
How to load the KG in python so that I can annotate new data?

### ISSUE THREAD

**Issue by abaheti95** [rloganiv/kglm-model#55]
I was interested in annotating new sentences with the KG. I saw the KG pkl file in [this google drive link](https://drive.google.com/file/d/1odypT9EDwtAYqzvRYnA2B_97hN_BWFnr/view?usp=sharing). However, there is no README or specifications about those files. Can you show me the code which reads these files? or just the specifications of these files?

**Comment by rloganiv** [comment]
The code for processing a Wikidata dump to the pkl file is located at: https://github.com/rloganiv/kglm-data.
