### ISSUE TITLE
Can you share the entity linker code which was used to annotate the linked-wiki-2 dataset

### ISSUE THREAD

**Issue by abaheti95** [rloganiv/kglm-model#56]
Hi, I wanted to annotate some data using the same format as you annotated linked-wikitext 2 dataset. Can you share the entity linker and the Stanford CoreNLP coreference code which was used to create that dataset?

**Comment by rloganiv** [comment]
Hi @abaheti95. My annotation code is available at: https://github.com/rloganiv/kglm-data.
