### ISSUE TITLE
@@END@@ mistakes in preprocessed data?

### ISSUE THREAD

**Issue by jcyk** [rloganiv/kglm-model#58]
Hi, thanks for open-sourcing the code and release the preprocessed data.

yet i find something strange in [the released data](https://drive.google.com/file/d/1odypT9EDwtAYqzvRYnA2B_97hN_BWFnr/view?usp=sharing). The @@END@@ sometimes appears in unreasonable places.

For example, in `valid.jsonl`, I found a case:

... Queen Elizabeth II and Prince Philip were guests of honor , making it the second Bond film premiere to be attended by the Queen , the first one being **You @@END@@ Only Live Twice** in 1967 ...

please note the @@END@@ is the middle of **You Only Live Twice**, which is an entity span.

and the entity is annotated with `{'source': 'WIKI', 'id': 'Q107761', 'relation': ['@@NEW@@'], 'parent_id': ['Q107761'], 'span': [2281, 2286]}`, resulting in an entity span **You @@END@@ Only Live Twice** according to the span indices.

there are many cases like the above.

**Comment by rloganiv** [comment]
Sentence boundaries were detected using SpaCy, it is possible that there are some mistakes.
